use_frameworks!

platform :ios, '11.0'

target 'TSPhotoPicker_Example' do
  pod 'TSPhotoPicker', :path => '../'
  pod 'GDPerformanceView-Swift'
  target 'TSPhotoPicker_Tests' do
    inherit! :search_paths

    
  end
end
